FROM gradle:8-jdk17-alpine AS build

WORKDIR /app

COPY build.gradle settings.gradle gradlew /app/
COPY gradle /app/gradle
COPY src /app/src

RUN gradle bootJar --no-daemon

FROM eclipse-temurin:17-jre-alpine

RUN adduser -S -D -H appuser
USER appuser

WORKDIR /app

COPY --from=build /app/build/libs/*.jar app.jar

ENV SPRING_PROFILES_ACTIVE=docker
ENV SERVER_PORT=8080

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
